### PR TITLE
Fix BL definition. BL is no call and does not read SP.

### PR DESCRIPTION
**Pull request by Rot127**
Fix for https://github.com/capstone-engine/capstone/issues/2234

### CODE REVIEW

**Review by wargio — APPROVED** [review]

**Review by XVilka — APPROVED** [review]

**Comment by Rot127** [comment]
Converted to draft because `BLR` is also wrong. And `BL` is considered a call.

**Comment by XVilka** [comment]
I wonder if it makes sense to ask LLVM developers about that

**Comment by Rot127** [comment]
It does. I added it already to [the list](https://github.com/capstone-engine/capstone/issues/2015).

**Comment by Rot127** [comment]
@kabeor Please take a look.

**Pull request merged**
