### PR TITLE
Rebase to LLVM 13.1 with cleanups

### PR DESCRIPTION
**Pull request by FlyGoat**

### CODE REVIEW

**Comment by kabeor** [comment]
amazing! But there are lots of conflicts need to be solved, can you have a look?

**Comment by FlyGoat** [comment]
> amazing! But there are lots of conflicts need to be solved, can you have a look?

This is because I had squashed those commits. It deserves a force push.

**Comment by FlyGoat** [comment]
Could you please just pull from my origin branch and force push to here?

**Comment by kabeor** [comment]
ok

**Comment by kabeor** [comment]
@FlyGoat A new idea. I will create a new branch based on llvm 13.0.1, than you pr, there should be no conflicts. We keep this branch for now.

**Comment by kabeor** [comment]
This pr has been move to https://github.com/capstone-engine/llvm-capstone/tree/dev, every change should PR to dev branch in the future. This PR closed.

**Pull request closed without merging**
