### PR TITLE
Sync with LLVM release/16.x

### PR DESCRIPTION
**Pull request by kabeor**

### CODE REVIEW

**Comment by kabeor** [comment]
Build failed, waitting until next week's commit sync.

**Comment by Rot127** [comment]
Would propose to get https://github.com/capstone-engine/llvm-capstone/pull/10 done first. After it is merged I do a rebase onto the newest `release/16.x` again.

**Comment by Rot127** [comment]
As @XVilka suggested we can just skip `v16` and go directly to `v17`. @kabeo any opjections?

**Comment by kabeor** [comment]
@Rot127 Sure, we can do that easily with CI now.

**Comment by kabeor** [comment]
Btw, CI failed since https://github.com/capstone-engine/llvm-capstone/actions/runs/5040615865, we should make sure it work before rebase to v17.

**Comment by Rot127** [comment]
@kabeor The current `release/16.x` branch has our auto-sync changes as well, if I see this correctly. Are you fine if we keep the `release/16.x` and future LLVM-release branches clean from `auto-sync` stuff and rebase the auto-sync onto it?

I think resolving conflicts is easier this way.
Also we do not accidentally merge LLVM stuff and overwrite auto-sync changes.

To make conflict resolving even easier, we can also think about squashing the `auto-sync` branch before every big rebase.

So in we end up with something like:


```
                 sqaush & rebase & rename
                 onto release/16.X
              +------------------------------>  auto-sync-16.X    <---- new PRs must go here.
              |                                        |
              |                                 (release/16.X)
             ...
          [commit C]
          [commit B]
          [commit A] 
          (auto-sync)
```

Might not be the best idea. Because it destroys the commit history for more convenience.

**Comment by kabeor** [comment]
@Rot127 

> Are you fine if we keep the release/16.x and future LLVM-release branches clean from auto-sync stuff and rebase the auto-sync onto it?

Yes, that would be great. I should have set the release/x.x branch to be protected.

**Comment by XVilka** [comment]
@kabeor @Rot127 LLVM just branched off to 17.x, I guess it's time to port this work on top of it. From what I saw in the git changes it shouldn't affect ARM and PPC, but will definetitely affect AArch64.
- https://github.com/llvm/llvm-project/tree/release/17.x
- https://discourse.llvm.org/t/llvm-17-0-0-rc1-released/72408
- https://discourse.llvm.org/t/llvm-17-0-0-rc2-released/72658
- https://discourse.llvm.org/t/llvm-17-0-0-rc3-released/72946
- https://discourse.llvm.org/t/llvm-17-0-0-rc4-released/73257

**Comment by kabeor** [comment]
Yep. Btw, when LLVM 17 offical version been released, the CI will auto creates a branch `release/17.x`.

**Comment by Rot127** [comment]
@kabeor Fancy! Will it include our changes? Or be equivalent to the LLVM release?

**Comment by kabeor** [comment]
@Rot127 It will just include llvm code. Any our changes still need to be merged into auto-sync.

**Comment by XVilka** [comment]
LLVM 17.0.1 was released finally:
- https://discourse.llvm.org/t/llvm-17-0-1-released/73549/4
- https://releases.llvm.org/17.0.1/docs/ReleaseNotes.html

**Comment by kabeor** [comment]
Let's see if CI works next Monday.

**Comment by Rot127** [comment]
closing this because we work on LLVM 18 now
https://github.com/capstone-engine/llvm-capstone/pull/45

**Pull request closed without merging**
